first_project/first_app/urls.py
from unicodedata import name
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'first_app'

urlpatterns = [
    path('', views.index, name='home'),
    path("users/", views.users, name="users"),
    path("form/", views.form_name_view, name="form"),
    path("new_user_form/", views.new_user_form, name="New User Form"),
    path("other/", views.other, name="other"),
    path("relative/", views.relative, name="relative")
]

first_project/first_project/urls.py
from django.contrib import admin
from django.urls import path, include
from first_app import views,urls
# from django.conf.urls.static import static
# from django.conf import settings

urlpatterns = [
    path('first_app/', include('first_app.urls')),
    path('admin/', admin.site.urls),
] 
# urlpatterns += staticfiles_urlpatterns()
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

first_project/first_app/models.py
from distutils.command.upload import upload
import email
from operator import mod
from statistics import mode
from tkinter import CASCADE
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model):
    top_name = models.CharField(max_length=264, unique=True)
    
    def __str__(self):
        return self.top_name
    
class WebPage(models.Model):
    topic = models.ForeignKey('Topic', on_delete=models.CASCADE)
    name = models.CharField(max_length=264, unique=True)
    url = models.URLField(unique=True)
    
    def __str__(self):
        return self.name

class AccessRecord(models.Model):
    name = models.ForeignKey('WebPage', on_delete=models.CASCADE)
    date = models.DateField()
    
    def __str__(self):
        return str(self.date)
    
class Users(models.Model):
    first_name = models.CharField(max_length=264)
    last_name = models.CharField(max_length=264)
    email = models.EmailField()
    
    def __str__(self):
        return str(self.first_name)
    
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pic', blank=True)
    
    def __str__(self):
        return self.user.username
    

first_project/first_app/forms.py
from dataclasses import fields
import email
from pyexpat import model
from django import forms
from django.http import request
from django.core import validators 
from first_app.models import Users, UserProfileInfo
from django.contrib.auth.models import User

def check_start_z(value):
    if value[0].lower() != 'z':
        raise forms.ValidationError("Name Needs to start with Z")
    
class FormName(forms.Form):
    name = forms.CharField(max_length=264, validators=[check_start_z    ])
    email = forms.EmailField()
    text = forms.CharField(widget=forms.Textarea)
    # botcacher = forms.CharField(required=False, widget=forms.HiddenInput)
    
class NewUserForm(forms.ModelForm):
    # fname = forms.CharField()
    # lname = forms.CharField()
    # email = forms.EmailField()
    class Meta:
        model = Users
        fields = "__all__"
        # if you want to exclude some fields from model 
        # exclude = ['field1', 'field2']
        # if you want to use some of the fields from model
        # include = ('field1', 'field2')
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    
    class Meta():
        model = User
        fields = ('username', 'email', 'password')
        
class UserProfileInfo(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')
        

first_project/first_app/views.py
from django.forms import forms
from django.shortcuts import render
from django.http import HttpResponse
from first_app.models import Topic, WebPage, AccessRecord, Users
from first_app import forms
from first_app.forms import NewUserForm

# Create your views here.
def index(request):
    my_data = {'name': 'Deep', 'age': 22}
    webpage_list = AccessRecord.objects.order_by('date')
    date_dict = {'access_record': webpage_list}
    return render(request, 'index.html', context = date_dict)

def users(request):
    user_list = Users.objects.all()
    users = {'users': user_list}
    return render(request, 'users.html', context=users)

def form_name_view(request):
    form = forms.FormName()
    if request.method == 'POST':
        form = forms.FormName(request.POST)
        if form.is_valid():
            print("SUCESSFULLY CONNECTED")
            print("Name:" + form.cleaned_data['name'])
            print("Email:" + form.cleaned_data['email'])
            print("Text:" + form.cleaned_data['text'])            
        
    return render(request, 'form.html', {'form': form})
    
def new_user_form(request):
    form = NewUserForm()
    
    if request.method == 'POST':
        form = NewUserForm(request.POST)
        
        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            raise Exception("Form is not Valid")

    return render(request, 'signup.html', {'form': form})

def other(request):
    return render(request, 'other.html')

def relative(request):
    context = {'text': "hello deep", 'number': 100}
    return render(request, 'relative_url_template.html', context)

first_project/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- CSS only -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a
                class="nav-link active"
                aria-current="page"
                href="{% url 'first_app:home'%}"
                >Home</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'first_app:relative'%}">Link</a>
            </li>
            <li class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                id="navbarDropdown"
                role="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                Dropdown
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><hr class="dropdown-divider" /></li>
                <li>
                  <a class="dropdown-item" href="#">Something else here</a>
                </li>
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled">Disabled</a>
            </li>
          </ul>
          <form class="d-flex">
            <input
              class="form-control me-2"
              type="search"
              placeholder="Search"
              aria-label="Search"
            />
            <button class="btn btn-outline-success" type="submit">
              Search
            </button>
          </form>
        </div>
      </div>
    </nav>
    <div class="container">{% block body_block %} {% endblock %}</div>
  </body>
</html>

first_project/templates/form.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- CSS only -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <title>Form For Test</title>
  </head>
  <body>
    <div class="container">
      <h1>Fill Out the Form</h1>
      <form method="POST">
        {% csrf_token %} {{ form.as_p }}
        <input
          type="submit"
          name="submit"
          value="Submit"
          class="btn btn-primary"
        />
      </form>
    </div>
  </body>
</html>

first_project/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/mystyle.css' %}" />
    <title>My First App</title>
  </head>
  <body>
    <h1>Heyy I am Looking for Django Developer.....</h1>
    <div class="table">
      <h1>Records</h1>
      {% if access_record %}
      <table>
        <thead>
          <th>Site Name</th>
          <th>Date Accessed</th>
        </thead>
        <tbody>
          {% for rec in access_record %}
          <tr>
            <td>{{ rec.name }}</td>
            <td>{{ rec.date }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      {% endif %}
    </div>
  </body>
</html>

first_project/templates/other.html
<!DOCTYPE html>
{% extends 'base.html'%} 
{% block title%} Inherited Title {% endblock%} 
{% block body_block %}
<h1>Hey i am Inherited...</h1>
{% endblock %}

first_project/templates/relative_url_template.html
{% load myextras %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Relative</title>
  </head>
  <body>
    <h1>Relative Page...</h1>
    <a href="{% url 'first_app:other' %}">Click me to open other page</a>
    <h3>{{ text|cut:'deep' }}</h3>
    <h3>{{ number|add:"99" }}</h3>
  </body>
</html>

first_project/templates/signup.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- CSS only -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <title>Sign Up</title>
  </head>
  <body>
    <div class="container">
      <h1>Please Sign Up Here.....!!!</h1>
      <form method="POST">
        {{ form.as_p }} {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Sign Up" />
      </form>
    </div>
  </body>
</html>

first_project/templates/users.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/mystyle.css'%}" />
    <title>User Information</title>
  </head>
  <body>
    <h1>This is a User Information Page</h1>
    <ol class="ass" start="1">
      {% if users %} {% for user in users %}
      <li>User Info</li>
      <ul style="list-style-type: circle">
        <li>First Name: {{ user.first_name}}</li>
        <li>Last Name: {{ user.last_name}}</li>
        <li>Email: {{ user.email}}</li>
      </ul>
      {% endfor %} {% endif %}
    </ol>
  </body>
</html>