cbv_practice/basic_app/urls.py
from django import views
from django.contrib import admin
from django.urls import path
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    path('', views.SchoolListView.as_view(), name='list'),
    path('<int:pk>/', views.SchoolDetailView.as_view(), name='detail')

]

cbv_practice/cbv_practice/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path, include
from basic_app import urls, views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('basic_app/', include('basic_app.urls'))
]

cbv_practice/basic_app/models.py
from django.db import models

# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name

class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey('School', on_delete=models.CASCADE, related_name='students')

    def __str__(self):
        return self.name

cbv_practice/basic_app/views.py
from django.shortcuts import render
from django.views.generic import View,  TemplateView, ListView, DetailView
from django.http import HttpResponse
from . import models
# Create your views here.
class IndexView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['inject'] = "Basic Context Tutrial"
        return context

class SchoolListView(ListView):
    context_object_name = 'schools'
    model = models.School


class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School
    template_name = 'basic_app/school_detail.html'

cbv_practice/basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <title>{% block title %}{% endblock %}</title>
  </head>
  <nav class="navbar navbar-default navbar-static-top">
    <ul class="nav navbar-nav">
      <li><a class="navbar-brand" href="{% url 'basic_app:list' %}">Schools</a></li>
      <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
      <li><a href="#"></a></li>
    </ul>
  </nav>
  <body>
    {% block body %} {% endblock %}
  </body>
</html>

cbv_practice/basic_app/templates/basic_app/school_detail.html
{% extends "basic_app/basic_app_base.html" %}

{% block  body%}
    <div class="jumbotron">
      <h1>Welcome to the School Detail Page</h1>
      <h2>School Details: </h2>
      <p>Name: {{ school_detail.name }}</p>
      <p>Principal: {{ school_detail.principal }}</p>
      <p>Location: {{ school_detail.location }}</p>
    </div>

    {% for student in school_detail.students.all %}
    <h3>{{ student.name }} who is {{ student.age }} years old </h3>
    {% endfor %}
{% endblock%}

cbv_practice/basic_app/templates/basic_app/school_list.html
{% extends "basic_app/basic_app_base.html" %}

{% block  body%}
  <h1>Welcome to a List of all Schools....</h1>
  <ol>
    {% for school in schools %}
    <h2><li><a href="{{ school.id }}">{{ school }}</a></li></h2>
    {% endfor %}
  </ol>
{% endblock%}

cbv_practice/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- CSS only -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    {% block body %} {% endblock %}
  </body>
</html>

cbv_practice/templates/index.html
{% extends 'base.html' %} {% block body %}
<h1>HElllo World</h1>
<h2>Injected Context: {{ inject }}</h2>
{% endblock %}